### ISSUE TITLE
addressOnBus function purpose

### ISSUE THREAD

**Issue by pixelherodev** [jsanchezv/z80cpp#4]
I looked through the code and I'm not sure so I figured I might as well ask: what is the purpose of the addressOnBus function?

**Comment by jsanchezv** [comment]
That's an interesting question, my friend... :)

You should to look my JSpeccy project, that uses the class Z80Core, the big brother of z80cpp and the addressOnBUs method implementated in Spectrum.java class.

Basically, the Z80 CPU sometimes holds a value on address bus, probably without any control signal (M1, MREQ, IORQ, RD or WR). Generally, Z80 is doing that during refresh cycle, putting the pair IR on address bus, but sometimes do this during execution of some instructions  (i.e. LDI instruction holds the value in DE register in address bus by 2 clock cycles).

This isn't important for many platforms. But in the Sinclair ZX Spectrum it's a critical detail to emulate it correctly. The ZX Spectrum have a custom chip called "the ULA", and is responsible for update the screen. This chip is polling the memory area between 0x4000-0x7FFF and, when it needs to update the screen and sees that the Z80 is accesing to this area, then suspend the clock signal to Z80 CPU until it ends with his screen work, following a certain time pattern. That's called "contended memory" in ZX Spectrum jargon and can increment the needed time to execute an instruction by a variable number of clock ticks. More on this, the ULA does this dirty trick, not using the WAIT signal, with any value in address bus, without looking the MREQ and IORQ lines, so it applies the contention on all even I/O ports too!.

So, in z80cpp (and in Z80Core) no instruction updates the clock ticks needed for every instruction as do other Z80 cores. All instructions are executed in phases, following his Z80 internal working. A simple example is INC BC/DE/HL/SP. The Z80 User Manual states that the instruction lasts six clock cycles. But, really, are 3+1 for read opcode from memory and decode phases and 2 execution cycles with IR pair put in address bus.

Some Z80 cores can do simple optimizations on some instructions (as DJNZ), not reading the relative offset from memory when register B == 0. But the Z80 always read the offset and that's crucial detail to emulate correctly a Sinclair ZX Spectrum.

Naturally, when you compares the z80cpp raw speed with another Z80 cores, z80cpp is slower. But this implementation allows a finer emulation, that can be needed to emulate another platforms. The most usual is simply add the number of cycles passed to addressOnBus to your "tstates" variable. But z80cpp don't depend of a tstates variable, so you can obviate completely this variable and control the execution by number of instructions executed... or nothing.
